//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_Ratboy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacenamiento_Ensamble
    {
        public int idAlmacenamiento_Ensamble { get; set; }
        public int idAlmacenamiento_FK { get; set; }
        public int idEnsamble_FK { get; set; }
        public bool estatus { get; set; }
    
        public virtual Almacenamiento Almacenamiento { get; set; }
        public virtual Ensamble Ensamble { get; set; }
    }
}
