//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_Ratboy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class correoElectronico
    {
        public System.DateTime fecha { get; set; }
        public bool estatus { get; set; }
        public int campoAutogenerado { get; set; }
        public int idUsuario_FK { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
