//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_Ratboy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_pedido
    {
        public int idDetallePedido { get; set; }
        public int idPedido { get; set; }
        public int idComponente { get; set; }
        public int idModulo { get; set; }
        public int idMarca { get; set; }
        public string modelo { get; set; }
        public int cantidad { get; set; }
        public int precioUnitario { get; set; }
    
        public virtual componente componente { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual pedido pedido { get; set; }
    }
}
