//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_Ratboy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ensamble
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ensamble()
        {
            this.cuelloBotella = new HashSet<cuelloBotella>();
            this.modeloVideo = new HashSet<modeloVideo>();
            this.Perfiles = new HashSet<Perfiles>();
            this.PlacaMadre1 = new HashSet<PlacaMadre>();
        }
    
        public int idEnsamble { get; set; }
        public int idPlacaMadre { get; set; }
        public int idProcesador { get; set; }
        public int idRAM { get; set; }
        public int idAlmacenamiento { get; set; }
        public int idFuentePoder { get; set; }
        public int idTarjetaVideo { get; set; }
        public int idGabinete { get; set; }
        public bool estatus { get; set; }
        public int idEmpleado { get; set; }
    
        public virtual Almacenamiento Almacenamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuelloBotella> cuelloBotella { get; set; }
        public virtual LogEmpleado LogEmpleado { get; set; }
        public virtual PlacaMadre PlacaMadre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<modeloVideo> modeloVideo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Perfiles> Perfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlacaMadre> PlacaMadre1 { get; set; }
    }
}
