//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_Ratboy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ensamble
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ensamble()
        {
            this.Almacenamiento_Ensamble = new HashSet<Almacenamiento_Ensamble>();
            this.memoriaRAM_Ensamble = new HashSet<memoriaRAM_Ensamble>();
            this.pedido_ensamble = new HashSet<pedido_ensamble>();
            this.Perfil_Ensamble = new HashSet<Perfil_Ensamble>();
        }
    
        public int idEnsamble { get; set; }
        public int idPlacaMadre_FK { get; set; }
        public int idProcesador_FK { get; set; }
        public int idFuentePoder_FK { get; set; }
        public int idTarjetaVideo_FK { get; set; }
        public int idGabinete_FK { get; set; }
        public bool estatus { get; set; }
        public Nullable<int> idDisipador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Almacenamiento_Ensamble> Almacenamiento_Ensamble { get; set; }
        public virtual Disipadores Disipadores { get; set; }
        public virtual fuentePoder fuentePoder { get; set; }
        public virtual Gabinete Gabinete { get; set; }
        public virtual tarjetaVideo tarjetaVideo { get; set; }
        public virtual PlacaMadre PlacaMadre { get; set; }
        public virtual procesador procesador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<memoriaRAM_Ensamble> memoriaRAM_Ensamble { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido_ensamble> pedido_ensamble { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Perfil_Ensamble> Perfil_Ensamble { get; set; }
    }
}
