//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_Ratboy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class memoriaRAM
    {
        public int idRAM { get; set; }
        public string nombre { get; set; }
        public int idTipoMemoria { get; set; }
        public int cantidad { get; set; }
        public int velocidad { get; set; }
        public bool estatus { get; set; }
        public double costoVendedor { get; set; }
        public double costoVenta { get; set; }
        public string marca { get; set; }
        public int watts { get; set; }
    
        public virtual tipoMemoria tipoMemoria { get; set; }
    }
}
