//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_Ratboy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido_ensamble
    {
        public int pedido_id { get; set; }
        public byte[] fecha_pedido { get; set; }
        public int ensamble_id { get; set; }
        public Nullable<bool> estatus { get; set; }
        public int usuario_id { get; set; }
        public Nullable<int> departamento { get; set; }
    
        public virtual Ensamble Ensamble { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
