//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_Ratboy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfiles
    {
        public int idPerfil { get; set; }
        public string Nombre { get; set; }
        public string Nivel { get; set; }
        public int idEnsamble { get; set; }
        public Nullable<bool> estatus { get; set; }
    
        public virtual Ensamble Ensamble { get; set; }
    }
}
