//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_Ratboy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class procesador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public procesador()
        {
            this.cuelloBotella = new HashSet<cuelloBotella>();
            this.cuelloBotella1 = new HashSet<cuelloBotella>();
        }
    
        public int idProcesador { get; set; }
        public string nombre { get; set; }
        public int cantidadNucleos { get; set; }
        public int cantidadSubProcesos { get; set; }
        public int frecuenciaBasica { get; set; }
        public int idTipoMemoria { get; set; }
        public int idSocket { get; set; }
        public string graficosIntegrados { get; set; }
        public int optane { get; set; }
        public double costoProveedor { get; set; }
        public double costoVenta { get; set; }
        public string marca { get; set; }
        public bool estatus { get; set; }
        public Nullable<double> watts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuelloBotella> cuelloBotella { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuelloBotella> cuelloBotella1 { get; set; }
        public virtual socket socket { get; set; }
        public virtual tipoMemoria tipoMemoria { get; set; }
    }
}
