//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_Ratboy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarjetaVideo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tarjetaVideo()
        {
            this.cuelloBotella = new HashSet<cuelloBotella>();
            this.Ensamble = new HashSet<Ensamble>();
            this.modeloVideo = new HashSet<modeloVideo>();
        }
    
        public int idTarjetaVideo { get; set; }
        public string nombre { get; set; }
        public string arquitectura { get; set; }
        public decimal cudaCore { get; set; }
        public decimal frameBuffer { get; set; }
        public decimal velocidadReloj { get; set; }
        public decimal velocidadMemoria { get; set; }
        public string nombreModelo { get; set; }
        public bool estatus { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuelloBotella> cuelloBotella { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ensamble> Ensamble { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<modeloVideo> modeloVideo { get; set; }
    }
}
