//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_Ratboy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public int idRol { get; set; }
        public Nullable<int> userIdCliente { get; set; }
        public Nullable<int> userIdAdmin { get; set; }
        public string rol { get; set; }
    
        public virtual UsuariosCliente UsuariosCliente { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
