//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_Ratboy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.correoElectronico = new HashSet<correoElectronico>();
            this.LogEmpleado = new HashSet<LogEmpleado>();
        }
    
        public int idUsuario { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int tipo_id_FK { get; set; }
        public int estatus { get; set; }
        public int idPersona_FK { get; set; }
        public string correo { get; set; }

        public bool checkestatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<correoElectronico> correoElectronico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogEmpleado> LogEmpleado { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual tipo_usuarios tipo_usuarios { get; set; }
    }
}
