//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_Ratboy.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Usuarios
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int tipo_id { get; set; }
        public int estatus { get; set; }
        public bool checkestatus { get; set; }
        public virtual tipo_usuarios tipo_usuarios { get; set; }
    }
}
